/*
 * 花言葉 — 誕生花データ（366日分・2月29日を含む）
 *
 * 日付は年に依存しない "MM-DD" 形式で管理します。
 * 値は flowers.js の花 id の配列です（花の名前は書かず、id で参照します）。
 * 1日に複数の誕生花があるのが普通なので、すべて配列で持ちます。
 *
 * 花ごとの「誕生花の日付」や「月ごとの誕生花」は、このファイルから自動で作られます。
 * flowers.js 側に日付を二重に書かないでください。
 *
 * 参照元（sources）:
 *   hananokotoba … 花言葉-由来 https://hananokotoba.com/ の「365日誕生花カレンダー」
 *                   各日のページに掲載された花名を、id に置き換えて整理しました。
 *   ※ 誕生花は資料によって異なり、諸説があります。
 */
(function () {
  'use strict';

  window.HANA_BIRTHDAYS = {
    // 1月
    '01-01': ['fukujuso', 'snowdrop'],
    '01-02': ['robai', 'take'],
    '01-03': ['matsu', 'plum', 'crocus', 'fukujuso'],
    '01-04': ['fukujuso'],
    '01-05': ['misumiso', 'crocus'],
    '01-06': ['mansaku'],
    '01-07': ['seri', 'snowdrop', 'benjamin'],
    '01-08': ['violet', 'mansaku', 'mokuren'],
    '01-09': ['northpole'],
    '01-10': ['freesia', 'stock'],
    '01-11': ['misumiso', 'seri'],
    '01-12': ['alyssum'],
    '01-13': ['cattleya'],
    '01-14': ['cyclamen', 'cymbidium'],
    '01-15': ['oncidium'],
    '01-16': ['dendrobium', 'snapdragon', 'snowdrop'],
    '01-17': ['cymbidium'],
    '01-18': ['primula', 'sanshuyu'],
    '01-19': ['yukiyanagi', 'matsu', 'shunran'],
    '01-20': ['calendula', 'ranunculus'],
    '01-21': ['robai', 'crocus', 'ivy', 'yukiyanagi'],
    '01-22': ['anthurium', 'anemone', 'guzmania', 'winter-jasmine'],
    '01-23': ['snowflake'],
    '01-24': ['freesia'],
    '01-25': ['primula', 'fuchsia', 'hakobe'],
    '01-26': ['sensitive-plant'],
    '01-27': ['plumeria', 'heliotrope', 'rowan'],
    '01-28': ['nemophila', 'snowflake', 'katakuri', 'gazania'],
    '01-29': ['ranunculus'],
    '01-30': ['muscari'],
    '01-31': ['crocus', 'sensitive-plant', 'mansaku'],

    // 2月
    '02-01': ['marguerite'],
    '02-02': ['snowdrop'],
    '02-03': ['camellia'],
    '02-04': ['boke'],
    '02-05': ['okinagusa', 'japanese-primrose', 'boke'],
    '02-06': ['rape-blossom'],
    '02-07': ['forget-me-not'],
    '02-08': ['peony', 'calendula', 'yukinoshita', 'hotokenoza'],
    '02-09': ['calendula'],
    '02-10': ['daphne', 'bergenia'],
    '02-11': ['freesia', 'gerbera', 'veronica-persica', 'kalmia'],
    '02-12': ['forsythia'],
    '02-13': ['edelweiss', 'rhodanthe'],
    '02-14': ['chamomile', 'mimosa', 'cineraria'],
    '02-15': ['daisy', 'mitsumata'],
    '02-16': ['bay-laurel', 'african-violet', 'daffodil'],
    '02-17': ['snowflake'],
    '02-18': ['dandelion'],
    '02-19': ['mokuren', 'primula', 'dandelion'],
    '02-20': ['kalmia', 'rhododendron', 'winter-jasmine', 'stock'],
    '02-21': ['violet'],
    '02-22': ['mukuge', 'rhodanthe', 'freesia'],
    '02-23': ['poppy', 'daphne', 'apricot'],
    '02-24': ['amaryllis', 'crocus', 'periwinkle'],
    '02-25': ['kalanchoe', 'ranunculus', 'rose', 'yucca'],
    '02-26': ['snowdrop', 'fukujuso', 'muscari', 'rhodanthe'],
    '02-27': ['ornithogalum', 'scilla'],
    '02-28': ['bay-laurel', 'misumiso', 'helichrysum'],
    '02-29': ['forget-me-not', 'armeria', 'money-tree'],

    // 3月
    '03-01': ['cornflower'],
    '03-02': ['ranunculus'],
    '03-03': ['peach'],
    '03-04': ['azalea'],
    '03-05': ['clivia', 'cornflower', 'linaria'],
    '03-06': ['daisy'],
    '03-07': ['campanula', 'nirinso', 'okinagusa'],
    '03-08': ['blue-star'],
    '03-09': ['asebi'],
    '03-10': ['lupinus', 'shasta-daisy'],
    '03-11': ['yukiyanagi', 'california-poppy'],
    '03-12': ['anemone', 'broom', 'tsukushi'],
    '03-13': ['ikariso', 'anemone', 'dandelion', 'alstroemeria'],
    '03-14': ['chamomile', 'alyssum', 'blue-daisy'],
    '03-15': ['clivia', 'iberis', 'forget-me-not', 'white-lace-flower'],
    '03-16': ['cercis', 'hanakaido'],
    '03-17': ['lupinus', 'anthurium', 'sanshuyu'],
    '03-18': ['dogwood', 'tosamizuki'],
    '03-19': ['thistle'],
    '03-20': ['sweet-pea', 'mitsumata'],
    '03-21': ['mansaku', 'baimo'],
    '03-22': ['forsythia', 'tulip', 'renge', 'mukuge', 'cornflower', 'iberis'],
    '03-23': ['dandelion', 'delphinium', 'gladiolus', 'alyssum', 'bergenia'],
    '03-24': ['katakuri', 'kobushi', 'california-poppy'],
    '03-25': ['alstroemeria', 'hanakaido'],
    '03-26': ['hananira', 'shunran'],
    '03-27': ['digitalis', 'bridal-veil'],
    '03-28': ['yamabuki', 'ebine'],
    '03-29': ['gobo', 'dandelion', 'strawberry', 'plum'],
    '03-30': ['broom', 'armeria'],
    '03-31': ['strawberry', 'nigella'],

    // 4月
    '04-01': ['cherry-blossom', 'marguerite'],
    '04-02': ['clover'],
    '04-03': ['geranium', 'adiantum', 'china-aster'],
    '04-04': ['babys-breath', 'japanese-plum'],
    '04-05': ['wisteria', 'forget-me-not', 'hanakaido'],
    '04-06': ['nasturtium', 'anemone', 'fukujuso'],
    '04-07': ['dimorphotheca', 'crocus', 'adiantum'],
    '04-08': ['moss-phlox', 'renge', 'apple', 'hanakaido'],
    '04-09': ['mimosa', 'cherry-blossom', 'okinagusa'],
    '04-10': ['pansy', 'linaria', 'china-aster', 'periwinkle'],
    '04-11': ['hyacinth'],
    '04-12': ['apricot', 'peach'],
    '04-13': ['strawberry', 'coreopsis'],
    '04-14': ['dodan', 'broom', 'harujion', 'blue-star', 'utsugi'],
    '04-15': ['snapdragon', 'godetia'],
    '04-16': ['snowflake', 'catchfly', 'renge-tsutsuji'],
    '04-17': ['iris', 'pothos', 'larkspur'],
    '04-18': ['alstroemeria'],
    '04-19': ['thistle', 'delphinium', 'ichihatsu'],
    '04-20': ['moss-phlox', 'pear', 'dimorphotheca', 'ixia'],
    '04-21': ['nigella', 'cherry-blossom'],
    '04-22': ['china-aster', 'catchfly'],
    '04-23': ['campanula'],
    '04-24': ['geranium', 'kodemari'],
    '04-25': ['bluebell', 'baimo'],
    '04-26': ['scabiosa', 'ajuga', 'ebine'],
    '04-27': ['shaga'],
    '04-28': ['japanese-primrose', 'mock-orange'],
    '04-29': ['wisteria'],
    '04-30': ['kalmia', 'pear', 'ichihatsu'],

    // 5月
    '05-01': ['edelweiss', 'lily-of-the-valley', 'mitsuba-tsutsuji'],
    '05-02': ['lily-of-the-valley', 'phlox'],
    '05-03': ['clematis', 'dandelion', 'mizubasho'],
    '05-04': ['yamabuki', 'stokesia', 'rose'],
    '05-05': ['iris'],
    '05-06': ['gardenia'],
    '05-07': ['mokuren', 'statice', 'egonoki'],
    '05-08': ['rhododendron', 'campanula', 'water-lily'],
    '05-09': ['clematis', 'kiri'],
    '05-10': ['iris', 'ageratum'],
    '05-11': ['apple', 'nasturtium'],
    '05-12': ['astilbe', 'thunbergia'],
    '05-13': ['hawthorn', 'california-poppy'],
    '05-14': ['peony'],
    '05-15': ['dokudami', 'campanula'],
    '05-16': ['allium', 'ixia'],
    '05-17': ['fuchsia', 'exacum'],
    '05-18': ['petunia', 'japanese-primrose', 'mock-orange'],
    '05-19': ['satsuki', 'bottlebrush'],
    '05-20': ['katabami', 'shasta-daisy'],
    '05-21': ['babys-breath', 'larkspur'],
    '05-22': ['fuchsia', 'azalea'],
    '05-23': ['digitalis', 'godetia'],
    '05-24': ['heliotrope'],
    '05-25': ['ranunculus', 'pansy', 'yuzu', 'hyssop'],
    '05-26': ['geranium', 'olive', 'sandersonia'],
    '05-27': ['feverfew', 'ebine', 'odemari'],
    '05-28': ['amaryllis', 'lily-of-the-valley', 'gloriosa', 'veronica'],
    '05-29': ['nigella', 'columbine'],
    '05-30': ['amaryllis', 'geranium', 'exacum', 'atsumoriso'],
    '05-31': ['lupinus', 'wisteria', 'scilla'],

    // 6月
    '06-01': ['astilbe', 'babys-breath', 'feverfew'],
    '06-02': ['thyme'],
    '06-03': ['hydrangea', 'honeysuckle'],
    '06-04': ['nikko-kisuge', 'utsugi'],
    '06-05': ['dahlia', 'marigold', 'hotarubukuro'],
    '06-06': ['penstemon'],
    '06-07': ['gardenia', 'tsutsuji', 'benjamin', 'white-lace-flower'],
    '06-08': ['jasmine', 'southern-magnolia'],
    '06-09': ['sweet-pea'],
    '06-10': ['acanthus'],
    '06-11': ['agapanthus', 'safflower'],
    '06-12': ['lilac', 'yucca'],
    '06-13': ['digitalis', 'bridal-veil', 'thunbergia'],
    '06-14': ['gladiolus'],
    '06-15': ['carnation', 'kousa'],
    '06-16': ['tuberose'],
    '06-17': ['yellow-cosmos', 'liatris'],
    '06-18': ['thyme', 'hollyhock', 'rose-campion'],
    '06-19': ['rose'],
    '06-20': ['veronica', 'chestnut'],
    '06-21': ['evening-primrose'],
    '06-22': ['honeysuckle', 'gamazumi'],
    '06-23': ['hollyhock', 'miyakowasure', 'biyouyanagi'],
    '06-24': ['verbena', 'otogiriso'],
    '06-25': ['bindweed', 'montbretia'],
    '06-26': ['pentas', 'gazania', 'biyouyanagi'],
    '06-27': ['calla', 'passion-flower', 'rhodanthe'],
    '06-28': ['lisianthus', 'geranium'],
    '06-29': ['agapanthus', 'dimorphotheca'],
    '06-30': ['gardenia', 'honeysuckle', 'scabiosa'],

    // 7月
    '07-01': ['himeyuri', 'clematis', 'matsubagiku', 'feijoa'],
    '07-02': ['snapdragon', 'clematis'],
    '07-03': ['lotus', 'himeyuri', 'matsubagiku'],
    '07-04': ['nejibana', 'mokuren', 'stokesia'],
    '07-05': ['lavender', 'lobelia', 'hamanasu', 'penstemon'],
    '07-06': ['sunflower', 'morning-glory', 'dayflower', 'hamayu'],
    '07-07': ['water-lily', 'gardenia'],
    '07-08': ['hozuki', 'lotus', 'campanula'],
    '07-09': ['linden', 'hosta'],
    '07-10': ['hotarubukuro', 'gloxinia', 'snapdragon', 'lavender'],
    '07-11': ['hibiscus', 'acanthus', 'fuchsia', 'echinops'],
    '07-12': ['yarrow', 'lisianthus'],
    '07-13': ['gladiolus', 'water-hyacinth', 'amaranthus'],
    '07-14': ['dianthus', 'trumpet-vine', 'rose', 'phlox'],
    '07-15': ['silk-tree', 'rose', 'natsutsubaki'],
    '07-16': ['portulaca', 'amaryllis', 'stock', 'ginger-lily'],
    '07-17': ['bindweed', 'hosta', 'hamayu'],
    '07-18': ['marigold', 'verbena', 'butterfly-weed'],
    '07-19': ['aconitum', 'epiphyllum'],
    '07-20': ['lisianthus', 'sunflower'],
    '07-21': ['rudbeckia', 'mint', 'silk-tree'],
    '07-22': ['petunia', 'dianthus', 'liatris', 'matsuyoigusa'],
    '07-23': ['allium', 'cypress-vine', 'ginger-lily'],
    '07-24': ['lily', 'peony', 'tree-peony', 'water-lily', 'nikko-kisuge'],
    '07-25': ['impatiens', 'aconitum'],
    '07-26': ['bougainvillea', 'larkspur', 'coreopsis'],
    '07-27': ['geranium', 'obedient-plant'],
    '07-28': ['four-oclock', 'dayflower', 'dianthus'],
    '07-29': ['cactus', 'dahlia'],
    '07-30': ['periwinkle', 'linden'],
    '07-31': ['rudbeckia'],

    // 8月
    '08-01': ['four-oclock'],
    '08-02': ['bellflower', 'canna', 'sunflower', 'cornflower', 'yarrow'],
    '08-03': ['moss-rose', 'canna', 'buddleja', 'santolina'],
    '08-04': ['tritoma', 'phlox'],
    '08-05': ['erica', 'spiderwort', 'sunflower'],
    '08-06': ['zinnia', 'morning-glory', 'torenia'],
    '08-07': ['pomegranate'],
    '08-08': ['cleome', 'anthurium', 'azalea'],
    '08-09': ['oleander', 'streptocarpus'],
    '08-10': ['hibiscus', 'cypress-vine'],
    '08-11': ['geranium', 'sanvitalia'],
    '08-12': ['black-lily', 'oleander', 'tansy'],
    '08-13': ['sagiso', 'canna', 'goldenrod'],
    '08-14': ['globe-amaranth', 'common-mallow', 'ammobium'],
    '08-15': ['lotus', 'montbretia'],
    '08-16': ['ominaeshi', 'datura'],
    '08-17': ['silk-tree'],
    '08-18': ['coleus', 'cleome', 'edelweiss'],
    '08-19': ['canna', 'goldenrod', 'rose-campion'],
    '08-20': ['freesia'],
    '08-21': ['blueberry', 'sagiso', 'moss-rose'],
    '08-22': ['curcuma'],
    '08-23': ['epiphyllum', 'four-oclock', 'linden'],
    '08-24': ['celosia', 'cypress-vine'],
    '08-25': ['burnet', 'rudbeckia', 'anthurium'],
    '08-26': ['mukuge', 'rose-campion', 'new-york-aster'],
    '08-27': ['balsam', 'yugao', 'hypericum'],
    '08-28': ['bellflower', 'currant'],
    '08-29': ['crape-myrtle', 'celosia', 'clover', 'china-aster', 'begonia-grandis'],
    '08-30': ['evening-primrose', 'goldenrod'],
    '08-31': ['gentian', 'salvia', 'hibiscus', 'sunflower', 'clover', 'renge'],

    // 9月
    '09-01': ['spathiphyllum', 'bellflower', 'oniyuri'],
    '09-02': ['tuberose'],
    '09-03': ['marguerite'],
    '09-04': ['datura', 'grape', 'montbretia'],
    '09-05': ['celosia', 'ominaeshi'],
    '09-06': ['nasturtium', 'misohagi'],
    '09-07': ['black-lily', 'hamanasu'],
    '09-08': ['zephyranthes', 'balsam'],
    '09-09': ['chrysanthemum'],
    '09-10': ['dahlia', 'begonia-grandis', 'hyssop'],
    '09-11': ['aloe', 'mukuge', 'butterfly-weed'],
    '09-12': ['indigo', 'clematis'],
    '09-13': ['zephyranthes', 'buddleja'],
    '09-14': ['japanese-anemone', 'ageratum'],
    '09-15': ['susuki'],
    '09-16': ['akane', 'gentian', 'pentas'],
    '09-17': ['balloon-vine', 'misebaya'],
    '09-18': ['balsam', 'thistle'],
    '09-19': ['salvia'],
    '09-20': ['red-spider-lily', 'yaburan'],
    '09-21': ['colchicum', 'sanvitalia'],
    '09-22': ['globe-amaranth', 'akane', 'sawagikyo'],
    '09-23': ['red-spider-lily'],
    '09-24': ['hagi', 'grape'],
    '09-25': ['petunia', 'amaranthus'],
    '09-26': ['lotus', 'portulaca', 'scarlet-rosemallow'],
    '09-27': ['cosmos', 'torenia'],
    '09-28': ['fujibakama', 'aster', 'helenium'],
    '09-29': ['portulaca', 'apple', 'thunbergia'],
    '09-30': ['monstera', 'zephyranthes', 'japanese-anemone'],

    // 10月
    '10-01': ['scarlet-rosemallow'],
    '10-02': ['coleus', 'apricot'],
    '10-03': ['obedient-plant'],
    '10-04': ['salvia', 'white-lace-flower'],
    '10-05': ['cleome'],
    '10-06': ['ominaeshi', 'yaburan'],
    '10-07': ['osmanthus', 'rose'],
    '10-08': ['japanese-anemone'],
    '10-09': ['toad-lily'],
    '10-10': ['bouvardia', 'sanvitalia'],
    '10-11': ['coleus', 'misohagi'],
    '10-12': ['gerbera', 'helenium'],
    '10-13': ['nerine', 'scarlet-rosemallow', 'shimotsuke'],
    '10-14': ['cattleya', 'new-york-aster'],
    '10-15': ['japanese-anemone', 'misebaya'],
    '10-16': ['aster'],
    '10-17': ['nerine', 'beautyberry', 'grape'],
    '10-18': ['begonia'],
    '10-19': ['gloriosa', 'goldenrod', 'crown-of-thorns'],
    '10-20': ['gentian', 'buddleja', 'exacum'],
    '10-21': ['thistle'],
    '10-22': ['susuki', 'rose'],
    '10-23': ['datura', 'akebi'],
    '10-24': ['plum', 'ageratum', 'chestnut'],
    '10-25': ['maple'],
    '10-26': ['ginkgo', 'yaburan', 'thunbergia'],
    '10-27': ['lantana'],
    '10-28': ['pachira', 'burnet'],
    '10-29': ['epiphyllum', 'streptocarpus', 'ageratum'],
    '10-30': ['petunia', 'lobelia'],
    '10-31': ['calla', 'heliconia'],

    // 11月
    '11-01': ['karin', 'akebi'],
    '11-02': ['lupinus', 'euryops'],
    '11-03': ['chamomile'],
    '11-04': ['saffron', 'beautyberry'],
    '11-05': ['pentas', 'moss-rose', 'matsubagiku'],
    '11-06': ['fujibakama'],
    '11-07': ['eucalyptus', 'cymbidium', 'euryops', 'tansy'],
    '11-08': ['holly'],
    '11-09': ['lantana', 'crown-of-thorns', 'manettia'],
    '11-10': ['fuyo'],
    '11-11': ['karasuuri'],
    '11-12': ['lemon'],
    '11-13': ['dendrobium', 'rowan'],
    '11-14': ['tree-dahlia', 'adiantum'],
    '11-15': ['red-spider-lily'],
    '11-16': ['christmas-rose'],
    '11-17': ['statice'],
    '11-18': ['himejoon', 'rowan', 'eucalyptus'],
    '11-19': ['otogiriso', 'burnet'],
    '11-20': ['karasuuri', 'tsuwabuki'],
    '11-21': ['ginkgo', 'campanula', 'amaranthus'],
    '11-22': ['angraecum', 'aloe', 'marguerite'],
    '11-23': ['strelitzia', 'pyracantha'],
    '11-24': ['cattleya', 'african-violet', 'gamazumi'],
    '11-25': ['nerine'],
    '11-26': ['gladiolus', 'hotarubukuro', 'manettia'],
    '11-27': ['ornamental-cabbage'],
    '11-28': ['oncidium', 'china-aster', 'sandersonia'],
    '11-29': ['begonia'],
    '11-30': ['babys-breath', 'atsumoriso', 'tsuwabuki'],

    // 12月
    '12-01': ['dracaena', 'anthurium'],
    '12-02': ['cineraria', 'heliconia'],
    '12-03': ['lavender'],
    '12-04': ['sasanqua'],
    '12-05': ['nandina', 'dracaena'],
    '12-06': ['yukinoshita', 'pyracantha'],
    '12-07': ['cyclamen', 'holly'],
    '12-08': ['nandina'],
    '12-09': ['poinsettia', 'loquat'],
    '12-10': ['christmas-cactus', 'camellia'],
    '12-11': ['kalanchoe'],
    '12-12': ['harujion', 'crown-of-thorns'],
    '12-13': ['christmas-rose', 'yatsude'],
    '12-14': ['matsu'],
    '12-15': ['monstera', 'daphne'],
    '12-16': ['strelitzia'],
    '12-17': ['freesia'],
    '12-18': ['cymbidium'],
    '12-19': ['snowflake'],
    '12-20': ['pineapple', 'loquat'],
    '12-21': ['platanus'],
    '12-22': ['african-violet', 'money-tree'],
    '12-23': ['cattleya', 'cineraria', 'spathiphyllum'],
    '12-24': ['mistletoe', 'northpole'],
    '12-25': ['rose', 'holly', 'blue-daisy', 'mistletoe'],
    '12-26': ['christmas-rose', 'bouvardia'],
    '12-27': ['pansy', 'yatsude'],
    '12-28': ['pomegranate', 'tsuwabuki'],
    '12-29': ['hozuki'],
    '12-30': ['ornamental-cabbage', 'manettia'],
    '12-31': ['yuzu', 'euryops']
  };

  window.HANA_BIRTHDAY_SOURCES = {
    hananokotoba: { label: '花言葉-由来', url: 'https://hananokotoba.com/calendar/' }
  };
})();
