/*
 * 花言葉 — 花データ
 *
 * 花を追加・修正するときは、この配列に1件ずつオブジェクトを追加してください。
 *
 *  id            英字の識別子（写真ファイル名にも使用: images/flowers/<id>.webp）
 *  name          表示名
 *  kana          読み方（ひらがな）。五十音の並び替え・検索に使用
 *  emoji         シェア時に使う絵文字（省略可）
 *  meanings      代表的な花言葉
 *  colorMeanings 色別の花言葉（一般的なものがある花のみ）
 *                { color, hex, meanings, note? }
 *  categories    気持ち（categories.js の feelings の id）
 *  recipients    贈る相手（categories.js の recipients の id）
 *  scenes        シーン（categories.js の scenes の id）
 *  season        開花時期のめやす
 *  description   ひとことで表す花の紹介
 *  origin        花言葉の由来
 *  trivia        豆知識
 *  message       「今日の花」に表示する一言
 *  point         一覧で表示する、おすすめの理由
 *  look          画像がないときのイラスト設定 { shape, colors: [花びら, 花びら2, 中心] }
 *                shape: round / daisy / star / cup / bell / cluster / layered / leaf / spike / trumpet
 *
 * ※ 花言葉には諸説あります。一般的に広く紹介されているものを掲載しています。
 */
(function () {
  'use strict';

  window.HANA_FLOWERS = [
    {
      id: 'ivy', name: 'アイビー', kana: 'あいびー', emoji: '🌿',
      meanings: ['永遠の愛', '友情', '誠実', '結婚'],
      categories: ['love', 'friendship', 'sincerity'],
      recipients: ['partner', 'friend', 'special'],
      scenes: ['wedding', 'anniversary', 'proposal'],
      season: '通年（葉を楽しむ植物）',
      description: 'つるを伸ばして広がる、丈夫で育てやすい観葉植物です。',
      origin: '壁や木にしっかり絡みつき、離れずに伸びていく姿から、変わらない愛や友情を表す言葉が生まれました。',
      trivia: '古代ギリシャでは結婚の儀式でアイビーを贈ったという話が伝わっています。ブーケに添えられることも多い植物です。',
      message: '離れていても、つながっている気持ちがあります。',
      point: '「永遠の愛」「友情」。長く寄り添う関係に。',
      look: { shape: 'leaf', colors: ['#bcd9b0', '#7fae7a', '#5c8a5a'] }
    },
    {
      id: 'morning-glory', name: 'アサガオ', kana: 'あさがお', emoji: '🌺',
      meanings: ['愛情の絆', '結束', 'はかない恋'],
      categories: ['love', 'friendship'],
      recipients: ['partner', 'friend', 'child'],
      scenes: ['anniversary'],
      season: '7〜9月',
      description: '夏の朝に咲き、昼にはしぼむ、日本の夏を代表する花です。',
      origin: 'つるが支柱にしっかり巻きついて伸びる様子から「絆」や「結束」、朝のうちにしぼむことから「はかない恋」といわれます。',
      trivia: '奈良時代ごろに中国から伝わり、もとは種を薬として使うための植物でした。江戸時代には品種改良が大流行しました。',
      message: '今朝の小さな約束が、明日の絆になります。',
      point: '「愛情の絆」。夏の思い出を分かち合う相手に。',
      look: { shape: 'trumpet', colors: ['#b9c6f5', '#7b8fe0', '#ffffff'] }
    },
    {
      id: 'hydrangea', name: 'アジサイ', kana: 'あじさい', emoji: '💠',
      meanings: ['辛抱強い愛情', '家族団らん', '移り気'],
      colorMeanings: [
        { color: '青', hex: '#8fa9e8', meanings: ['辛抱強い愛情', '知的'] },
        { color: 'ピンク', hex: '#f3a9c4', meanings: ['元気な女性', '強い愛情'] },
        { color: '白', hex: '#f4f1ea', meanings: ['寛容', 'ひたむきな愛情'] }
      ],
      categories: ['love', 'happiness', 'kindness'],
      recipients: ['family', 'parents'],
      scenes: ['mothersday', 'anniversary'],
      season: '6〜7月',
      description: '梅雨の季節をやさしく彩る、小さな花が集まった花です。',
      origin: '小さな花がたくさん寄り添って咲く姿から「家族団らん」、咲きながら色が変わることから「移り気」といわれます。',
      trivia: '花の色は土の性質で変わり、酸性の土では青く、アルカリ性に近いとピンクになりやすいといわれます。花に見える部分の多くは装飾花（がく）です。',
      message: '雨の日も、寄り添えばやさしい景色になります。',
      point: '「家族団らん」。母の日にも人気の花。',
      look: { shape: 'cluster', colors: ['#b8c8f5', '#e7b6d8', '#ffffff'] }
    },
    {
      id: 'anemone', name: 'アネモネ', kana: 'あねもね', emoji: '🌸',
      meanings: ['はかない恋', '期待', '真実'],
      colorMeanings: [
        { color: '赤', hex: '#e2566a', meanings: ['君を愛す'] },
        { color: '白', hex: '#f6f3ee', meanings: ['真実', '期待', '希望'] },
        { color: '紫', hex: '#a07ad0', meanings: ['あなたを信じて待つ'] },
        { color: 'ピンク', hex: '#f4a6c0', meanings: ['待望'] }
      ],
      categories: ['love', 'hope'],
      recipients: ['partner', 'special'],
      scenes: ['confession'],
      season: '2〜5月',
      description: '春に鮮やかな色の花を咲かせる、存在感のある花です。',
      origin: 'ギリシャ神話で、美少年アドニスの流した血からこの花が咲いたという物語があり、そこから「はかない恋」の花言葉が生まれました。',
      trivia: '名前はギリシャ語で「風」を意味する言葉に由来するといわれ、英語ではウィンドフラワーとも呼ばれます。',
      message: '待っている時間も、きっと物語の一部です。',
      point: '白は「希望」、赤は「君を愛す」。色で想いを選べます。',
      look: { shape: 'round', colors: ['#f07a8c', '#d94a64', '#2f2a3a'] }
    },
    {
      id: 'amaryllis', name: 'アマリリス', kana: 'あまりりす', emoji: '🌺',
      meanings: ['輝くばかりの美しさ', '誇り', 'おしゃべり'],
      categories: ['respect', 'happiness'],
      recipients: ['friend', 'boss', 'special'],
      scenes: ['birthday', 'thanks'],
      season: '4〜6月',
      description: '太い茎の先に、大きなラッパ形の花を咲かせる球根植物です。',
      origin: '大きく堂々とした花姿から「輝くばかりの美しさ」「誇り」、横向きにいくつも並んで咲く様子から「おしゃべり」といわれます。',
      trivia: '球根ひとつから太い花茎が伸び、大輪の花を数輪咲かせます。',
      message: 'あなたの輝きを、あなた自身が信じてあげて。',
      point: '「輝くばかりの美しさ」。華やかなお祝いに。',
      look: { shape: 'star', colors: ['#f36d7d', '#d9344f', '#f7e39a'] }
    },
    {
      id: 'alstroemeria', name: 'アルストロメリア', kana: 'あるすとろめりあ', emoji: '🌷',
      meanings: ['持続', '未来への憧れ', '凛々しさ', 'エキゾチック'],
      categories: ['future', 'friendship', 'hope'],
      recipients: ['friend', 'teacher', 'boss'],
      scenes: ['graduation', 'entrance', 'farewell', 'birthday'],
      season: '5〜7月（切り花は通年）',
      description: '花びらに入る筋模様が美しい、南米原産の花です。',
      origin: '切り花にしても長く咲き続ける花持ちのよさから「持続」、すっと伸びた姿から「未来への憧れ」といわれます。',
      trivia: 'スウェーデンの植物学者アルストレーメルの名前にちなんで名づけられました。',
      message: '憧れは、未来へ続く道しるべ。',
      point: '「未来への憧れ」。門出や送別に贈りやすい花。',
      look: { shape: 'star', colors: ['#fbb58f', '#f38b73', '#9a5a4a'] }
    },
    {
      id: 'iris', name: 'アイリス', kana: 'あいりす', emoji: '💜',
      meanings: ['よい便り', 'メッセージ', '希望'],
      categories: ['hope', 'cheer'],
      recipients: ['friend', 'special'],
      scenes: ['cheer', 'entrance'],
      season: '4〜5月',
      description: 'すらりと伸びた葉と、青紫の上品な花が印象的な花です。',
      origin: 'ギリシャ神話で神々の伝言を虹にのって届ける女神イリスの名に由来し、「よい便り」「メッセージ」という花言葉がつきました。',
      trivia: '日本ではダッチアイリスなどが切り花として親しまれています。',
      message: 'うれしい知らせは、もうすぐそこまで来ています。',
      point: '「よい便り」。結果を待つ人への応援に。',
      look: { shape: 'star', colors: ['#9d8ae0', '#6a55c4', '#f5d562'] }
    },
    {
      id: 'plum', name: 'ウメ', kana: 'うめ', emoji: '🌸',
      meanings: ['高潔', '忍耐', '気品'],
      colorMeanings: [
        { color: '白', hex: '#f7f2ef', meanings: ['気品'] },
        { color: '赤', hex: '#e2587a', meanings: ['優美'] }
      ],
      categories: ['respect', 'cheer', 'health'],
      recipients: ['teacher', 'parents', 'boss'],
      scenes: ['cheer', 'entrance'],
      season: '2〜3月',
      description: 'まだ寒い早春に、香り高い花を咲かせる木です。',
      origin: '寒さの残る時期にいち早く凛と咲く姿から「忍耐」「高潔」といわれます。',
      trivia: '春を告げることから「春告草（はるつげぐさ）」という別名があります。学問の神様・菅原道真が愛した花としても知られます。',
      message: '寒い日々を越えた人にだけ、咲く花があります。',
      point: '「忍耐」「高潔」。受験や挑戦の応援に。',
      look: { shape: 'round', colors: ['#fbd0db', '#f199b0', '#e7b74a'] }
    },
    {
      id: 'edelweiss', name: 'エーデルワイス', kana: 'えーでるわいす', emoji: '🤍',
      meanings: ['大切な思い出', '勇気', '尊い記憶'],
      categories: ['comfort', 'cheer', 'respect'],
      recipients: ['friend', 'special'],
      scenes: ['farewell', 'cheer'],
      season: '6〜9月',
      description: 'アルプスなどの高山に咲く、白い綿毛に包まれた花です。',
      origin: '険しい高山に咲くため、摘みに行くには勇気が必要だったことから「勇気」の花言葉がついたといわれます。',
      trivia: 'スイスやオーストリアの象徴的な花で、名前はドイツ語で「高貴な白」を意味します。',
      message: '思い出は、次の一歩をくれる勇気になります。',
      point: '「大切な思い出」。別れや旅立ちの記念に。',
      look: { shape: 'star', colors: ['#f8f6f0', '#dcd8cc', '#e9d77f'] }
    },
    {
      id: 'carnation', name: 'カーネーション', kana: 'かーねーしょん', emoji: '💐',
      meanings: ['無垢で深い愛', '感動'],
      colorMeanings: [
        { color: '赤', hex: '#e2566a', meanings: ['母への愛', '真実の愛'] },
        { color: 'ピンク', hex: '#f5a6bf', meanings: ['感謝', '温かい心', '上品'] },
        { color: '白', hex: '#f6f3ee', meanings: ['純粋な愛', '尊敬'] },
        { color: '黄', hex: '#f3d56b', meanings: ['軽蔑', '嫉妬'], note: '贈り物では避けられることがあります' }
      ],
      categories: ['love', 'thanks', 'kindness'],
      recipients: ['parents', 'family'],
      scenes: ['mothersday', 'thanks', 'birthday'],
      season: '4〜6月',
      description: 'フリルのような花びらが愛らしい、母の日の定番の花です。',
      origin: 'アメリカで亡き母をしのんで白いカーネーションを配ったことが母の日の始まりとされ、母への愛を表す花になりました。',
      trivia: '花持ちがよく、色の種類がとても豊富です。母の日には赤やピンクが特に人気です。',
      message: 'いつもの「ありがとう」を、今日は少しだけ特別に。',
      point: 'ピンクは「感謝」。お母さんへの定番の花。',
      look: { shape: 'layered', colors: ['#f7a9bf', '#e8718f', '#e8718f'] }
    },
    {
      id: 'gerbera', name: 'ガーベラ', kana: 'がーべら', emoji: '🌼',
      meanings: ['希望', '常に前進'],
      colorMeanings: [
        { color: '赤', hex: '#e2566a', meanings: ['神秘', '燃える神秘の愛'] },
        { color: 'ピンク', hex: '#f5a6bf', meanings: ['感謝', '崇高美'] },
        { color: '白', hex: '#f6f3ee', meanings: ['希望', '律儀'] },
        { color: '黄', hex: '#f3d56b', meanings: ['究極の愛', '優しさ'] },
        { color: 'オレンジ', hex: '#f5a067', meanings: ['我慢強さ', '冒険心'] }
      ],
      categories: ['hope', 'cheer', 'thanks', 'happiness'],
      recipients: ['friend', 'family', 'child', 'boss'],
      scenes: ['birthday', 'cheer', 'visit', 'entrance', 'thanks'],
      season: '4〜5月、9〜10月',
      description: '丸く明るい花が、見る人を笑顔にしてくれる花です。',
      origin: '太陽に向かってまっすぐ咲く明るい花姿から、「希望」「常に前進」という前向きな花言葉がつきました。',
      trivia: '南アフリカ原産で、名前はドイツの医師・博物学者ゲルバーにちなみます。色数が多く、贈り物に使いやすい花です。',
      message: '今日もあなたらしく、一歩ずつ。',
      point: '「希望」「常に前進」。明るい応援の花。',
      look: { shape: 'daisy', colors: ['#fbb17d', '#f5845a', '#7a4a2a'] }
    },
    {
      id: 'babys-breath', name: 'カスミソウ', kana: 'かすみそう', emoji: '🤍',
      meanings: ['感謝', '幸福', '清らかな心', '無邪気'],
      categories: ['thanks', 'happiness', 'kindness'],
      recipients: ['family', 'friend', 'child', 'teacher', 'special'],
      scenes: ['thanks', 'wedding', 'birth', 'graduation'],
      season: '5〜7月（切り花は通年）',
      description: '小さな白い花が霞のように広がる、名脇役の花です。',
      origin: '小さな花がふんわり寄り添って咲く清らかな姿から、「感謝」「清らかな心」といわれます。',
      trivia: '英語では「Baby\'s breath（赤ちゃんの吐息）」と呼ばれます。ドライフラワーにも向いています。',
      message: '小さなやさしさが、今日を明るくしてくれます。',
      point: '「感謝」「幸福」。どんな花束にも寄り添います。',
      look: { shape: 'cluster', colors: ['#ffffff', '#f3eef2', '#e9e1e6'] }
    },
    {
      id: 'calla', name: 'カラー', kana: 'からー', emoji: '🤍',
      meanings: ['華麗なる美', '乙女のしとやかさ', '清浄'],
      categories: ['love', 'respect', 'happiness'],
      recipients: ['partner', 'special', 'boss'],
      scenes: ['wedding', 'proposal', 'anniversary'],
      season: '5〜7月',
      description: 'すっと巻いた花姿が上品な、洗練された印象の花です。',
      origin: '無駄のない凛とした花の形と、清らかな白い色から「華麗なる美」「清浄」といわれます。',
      trivia: '花びらに見える部分は「仏炎苞（ぶつえんほう）」と呼ばれる葉の一種です。ウエディングブーケでも人気があります。',
      message: 'シンプルなものほど、まっすぐ心に届きます。',
      point: '「華麗なる美」。結婚祝いのブーケにも。',
      look: { shape: 'trumpet', colors: ['#fbf8f2', '#e6e0d4', '#f2d46b'] }
    },
    {
      id: 'kalanchoe', name: 'カランコエ', kana: 'からんこえ', emoji: '🌼',
      meanings: ['幸福を告げる', 'たくさんの小さな思い出', 'おおらかな心'],
      categories: ['happiness', 'comfort', 'kindness'],
      recipients: ['friend', 'family', 'parents'],
      scenes: ['birthday', 'thanks'],
      season: '12〜5月',
      description: '肉厚の葉と小さな花の房がかわいらしい多肉植物です。',
      origin: '小さな花がたくさん集まって咲く様子から「たくさんの小さな思い出」「幸福を告げる」といわれます。',
      trivia: '日が短くなると花芽をつける「短日植物」です。花が長く楽しめ、鉢植えのギフトとしても人気です。',
      message: '小さな幸せを数えたら、きっと両手いっぱい。',
      point: '「幸福を告げる」。長く楽しめる鉢植えギフトに。',
      look: { shape: 'cluster', colors: ['#fca38a', '#f5746a', '#f7d86b'] }
    },
    {
      id: 'bellflower', name: 'キキョウ', kana: 'ききょう', emoji: '💜',
      meanings: ['永遠の愛', '誠実', '気品'],
      categories: ['love', 'sincerity', 'respect'],
      recipients: ['partner', 'parents', 'teacher'],
      scenes: ['anniversary', 'thanks'],
      season: '6〜9月',
      description: '星形の青紫の花が涼しげな、秋の七草のひとつです。',
      origin: '古くから日本で愛され、変わらない凛とした花の姿から「永遠の愛」「誠実」といわれます。',
      trivia: 'つぼみが風船のようにふくらむため、英語では「バルーンフラワー」と呼ばれます。',
      message: '変わらない想いは、静かに強く咲き続けます。',
      point: '「誠実」「永遠の愛」。上品に想いを伝えたいときに。',
      look: { shape: 'star', colors: ['#a998e6', '#7a63cc', '#e8e2f7'] }
    },
    {
      id: 'chrysanthemum', name: 'キク', kana: 'きく', emoji: '🏵️',
      meanings: ['高貴', '高潔', '真の愛'],
      colorMeanings: [
        { color: '白', hex: '#f6f3ee', meanings: ['真実'] },
        { color: '赤', hex: '#e2566a', meanings: ['あなたを愛しています'] },
        { color: '黄', hex: '#f3d56b', meanings: ['破れた恋'], note: '贈り物では避けられることがあります' }
      ],
      categories: ['respect', 'health', 'sincerity'],
      recipients: ['parents', 'teacher'],
      scenes: ['thanks'],
      season: '9〜11月',
      description: '日本の秋を代表する、気高い印象の花です。',
      origin: '古くから長寿を願う花として大切にされ、その気品ある姿から「高貴」「高潔」といわれます。',
      trivia: '皇室の紋章やパスポートの表紙にも描かれています。日本では仏花の印象もあるため、お見舞いでは洋菊やピンポンマムなどを選ぶと安心です。',
      message: '凛とした心は、どんな季節も美しい。',
      point: '「高貴」。長寿を願う花として敬老のお祝いにも。',
      look: { shape: 'layered', colors: ['#f8d977', '#eeb948', '#d99a2f'] }
    },
    {
      id: 'osmanthus', name: 'キンモクセイ', kana: 'きんもくせい', emoji: '🧡',
      meanings: ['謙虚', '気高い人', '初恋', '真実'],
      categories: ['respect', 'love', 'sincerity'],
      recipients: ['teacher', 'special', 'partner'],
      scenes: ['thanks', 'confession'],
      season: '9〜10月',
      description: '秋になると甘い香りで季節を知らせる、オレンジ色の小花の木です。',
      origin: '遠くまで届く豊かな香りに対して、花はとても小さく控えめなことから「謙虚」「気高い人」といわれます。',
      trivia: '中国原産で、日本にあるものの多くは雄株のため、実がほとんどなりません。三大香木のひとつです。',
      message: 'さりげない心づかいほど、遠くまで香ります。',
      point: '「気高い人」。尊敬する人へ、秋の贈り物に。',
      look: { shape: 'cluster', colors: ['#fbbf6d', '#f39a3a', '#fde1b5'] }
    },
    {
      id: 'gardenia', name: 'クチナシ', kana: 'くちなし', emoji: '🤍',
      meanings: ['とても幸せです', '喜びを運ぶ', '洗練'],
      categories: ['happiness', 'love'],
      recipients: ['partner', 'special'],
      scenes: ['wedding', 'anniversary'],
      season: '6〜7月',
      description: '初夏に甘い香りを漂わせる、白い花の木です。',
      origin: '甘く豊かな香りと真っ白な花が、幸せに満ちた気持ちを思わせることから「とても幸せです」といわれます。',
      trivia: '春のジンチョウゲ、秋のキンモクセイと並ぶ「三大香木」のひとつです。実が熟しても口を開かないことが名前の由来という説があります。',
      message: '「幸せ」は、声に出すともっと大きくなります。',
      point: '「とても幸せです」。ふたりの記念日に。',
      look: { shape: 'layered', colors: ['#fdfbf5', '#ece6d8', '#f3e3a3'] }
    },
    {
      id: 'christmas-rose', name: 'クリスマスローズ', kana: 'くりすますろーず', emoji: '🤍',
      meanings: ['私の不安を和らげて', 'いたわり', '追憶'],
      categories: ['comfort', 'kindness'],
      recipients: ['friend', 'family', 'special'],
      scenes: ['thanks'],
      season: '12〜3月',
      description: 'うつむくように咲く、冬から早春の庭の人気者です。',
      origin: '寒い季節に静かにうつむいて咲く姿が、そっと寄り添うように見えることから「いたわり」「私の不安を和らげて」といわれます。',
      trivia: '花びらに見える部分は「がく」で、色が長く残るため、花の時期が長く楽しめます。',
      message: '不安な日は、自分にもやさしくしてあげて。',
      point: '「いたわり」。そっと寄り添いたい人へ。',
      look: { shape: 'round', colors: ['#efe3ee', '#c9a9c9', '#e9dc8a'] }
    },
    {
      id: 'clematis', name: 'クレマチス', kana: 'くれまちす', emoji: '💜',
      meanings: ['精神の美', '旅人の喜び'],
      categories: ['respect', 'future'],
      recipients: ['teacher', 'friend'],
      scenes: ['farewell', 'graduation'],
      season: '4〜10月（品種による）',
      description: '大きく開く花が美しい、「つる性植物の女王」と呼ばれる花です。',
      origin: 'ヨーロッパでは道ばたの木々に絡んで木陰をつくり、旅人を休ませたことから「旅人の喜び」といわれます。',
      trivia: '花びらに見える部分は、実は「がく」です。品種が非常に多く、咲く時期もさまざまです。',
      message: '新しい道にも、やさしい木陰はきっとあります。',
      point: '「旅人の喜び」。新天地へ向かう人に。',
      look: { shape: 'star', colors: ['#c1a6ec', '#8c6ad6', '#f3e7a2'] }
    },
    {
      id: 'crocus', name: 'クロッカス', kana: 'くろっかす', emoji: '💜',
      meanings: ['青春の喜び', '切望'],
      categories: ['hope', 'future'],
      recipients: ['friend', 'child'],
      scenes: ['entrance', 'graduation'],
      season: '2〜4月',
      description: '早春、地面から顔を出すように咲く小さな球根の花です。',
      origin: '冬の終わりにいち早く咲き、春の訪れを喜ぶような姿から「青春の喜び」といわれます。',
      trivia: 'スパイスのサフランと同じ仲間です。日が当たると花が開き、夕方には閉じます。',
      message: '春は、待っている人のところへちゃんと来ます。',
      point: '「青春の喜び」。新生活を迎える人に。',
      look: { shape: 'cup', colors: ['#c3a8ee', '#9a78dc', '#f3c24a'] }
    },
    {
      id: 'clover', name: 'クローバー', kana: 'くろーばー', emoji: '🍀',
      meanings: ['幸運', '約束', '私を思って'],
      categories: ['happiness', 'love', 'friendship'],
      recipients: ['friend', 'partner', 'child', 'special'],
      scenes: ['cheer', 'birthday', 'visit'],
      season: '4〜7月',
      description: '三つ葉の葉と白く丸い花がかわいらしい植物（シロツメクサ）です。',
      origin: 'めったに見つからない四つ葉が幸運のしるしとされることから「幸運」の花言葉が広まりました。',
      trivia: '江戸時代、オランダから届いたガラス器の詰め物に使われていたことが「シロツメクサ（白詰草）」の名の由来です。',
      message: '幸運は、足もとで見つけてもらうのを待っています。',
      point: '「幸運」「約束」。小さなお守りのような贈り物に。',
      look: { shape: 'leaf', colors: ['#b7dca6', '#78b36a', '#5d9853'] }
    },
    {
      id: 'celosia', name: 'ケイトウ', kana: 'けいとう', emoji: '❤️',
      meanings: ['おしゃれ', '個性', '色あせぬ恋'],
      categories: ['love', 'cheer'],
      recipients: ['friend', 'special'],
      scenes: ['birthday', 'cheer'],
      season: '7〜11月',
      description: 'ビロードのような質感と、ユニークな形が目をひく花です。',
      origin: '独特の形と鮮やかな色から「おしゃれ」「個性」、色が長く残ることから「色あせぬ恋」といわれます。',
      trivia: '花の形がニワトリのとさかに似ていることから「鶏頭」と書きます。ドライフラワーにしても色がきれいに残ります。',
      message: 'あなたの「らしさ」は、それだけで魅力です。',
      point: '「個性」。自分らしさを大切にする人に。',
      look: { shape: 'spike', colors: ['#ef6a7e', '#c93c5c', '#9c2a45'] }
    },
    {
      id: 'cosmos', name: 'コスモス', kana: 'こすもす', emoji: '🌸',
      meanings: ['乙女の真心', '調和', '謙虚'],
      colorMeanings: [
        { color: 'ピンク', hex: '#f5a6bf', meanings: ['乙女の純潔'] },
        { color: '白', hex: '#f6f3ee', meanings: ['優美', '純潔'] },
        { color: '赤', hex: '#e2566a', meanings: ['愛情', '調和'] },
        { color: 'チョコレート', hex: '#7a3b3b', meanings: ['恋の終わり', '移り変わらぬ気持ち'] }
      ],
      categories: ['sincerity', 'kindness', 'love'],
      recipients: ['friend', 'partner', 'family'],
      scenes: ['birthday', 'thanks'],
      season: '9〜10月',
      description: '秋風にゆれる姿がやさしい、「秋桜」とも書く花です。',
      origin: '花びらが整然と並ぶ姿から、ギリシャ語で「秩序・調和」を意味する名がつき、「調和」の花言葉になりました。',
      trivia: 'メキシコ原産で、日本には明治時代に伝わったといわれます。',
      message: 'ゆれながらでも、まっすぐに咲けばいい。',
      point: '「乙女の真心」。秋のやさしい贈り物に。',
      look: { shape: 'round', colors: ['#f7b4cb', '#ec86a8', '#f2c94c'] }
    },
    {
      id: 'moth-orchid', name: 'コチョウラン', kana: 'こちょうらん', emoji: '🦋',
      meanings: ['幸福が飛んでくる', '純粋な愛'],
      categories: ['happiness', 'respect', 'love'],
      recipients: ['boss', 'parents', 'special'],
      scenes: ['birthday', 'wedding', 'farewell', 'anniversary'],
      season: '3〜5月（鉢物は通年流通）',
      description: '蝶が舞うような花が連なる、華やかで気品あるランです。',
      origin: '花の形がひらひら舞う蝶のように見えることから「幸福が飛んでくる」といわれます。',
      trivia: '花持ちがとてもよく、開店祝いや就任祝いなどお祝いの鉢植えの定番です。',
      message: '幸せは、ひらりと舞いこんでくるものです。',
      point: '「幸福が飛んでくる」。格式あるお祝いに。',
      look: { shape: 'round', colors: ['#fbf3f7', '#f0bfd4', '#e55b86'] }
    },
    {
      id: 'sasanqua', name: 'サザンカ', kana: 'さざんか', emoji: '🌺',
      meanings: ['困難に打ち克つ', 'ひたむきさ'],
      colorMeanings: [
        { color: '赤', hex: '#e2566a', meanings: ['謙譲'] },
        { color: '白', hex: '#f6f3ee', meanings: ['愛嬌'] },
        { color: 'ピンク', hex: '#f5a6bf', meanings: ['永遠の愛'] }
      ],
      categories: ['cheer', 'sincerity'],
      recipients: ['friend', 'family'],
      scenes: ['cheer'],
      season: '10〜12月',
      description: '冬の寒さのなかで咲く、ツバキに似た花です。',
      origin: '木枯らしが吹く寒い季節にも花を咲かせることから「困難に打ち克つ」といわれます。',
      trivia: 'ツバキは花ごと落ちるのに対し、サザンカは花びらが1枚ずつ散るのが見分けるポイントです。',
      message: '寒い日にこそ、心の花はよく咲きます。',
      point: '「困難に打ち克つ」。がんばる人へのエールに。',
      look: { shape: 'round', colors: ['#f59ab4', '#e0628a', '#f5d15b'] }
    },
    {
      id: 'cherry-blossom', name: 'サクラ', kana: 'さくら', emoji: '🌸',
      meanings: ['精神の美', '優美な女性', '純潔'],
      categories: ['future', 'hope', 'respect'],
      recipients: ['teacher', 'friend', 'child'],
      scenes: ['graduation', 'entrance', 'farewell'],
      season: '3〜4月',
      description: '日本の春を象徴する、淡いピンクの花です。',
      origin: '潔く咲いて散る姿が、日本人の美意識と重ねられ「精神の美」といわれるようになりました。',
      trivia: '現在最も多いソメイヨシノは、江戸時代末期に江戸の染井村（今の東京都豊島区）から広まったといわれます。',
      message: '出会いと別れの季節に、いちばんきれいな景色を。',
      point: '「精神の美」。卒業や入学の季節の花。',
      look: { shape: 'round', colors: ['#fcd6e0', '#f5a9bf', '#e9748f'] }
    },
    {
      id: 'saffron', name: 'サフラン', kana: 'さふらん', emoji: '💜',
      meanings: ['歓喜', '陽気', '節度の美'],
      categories: ['happiness', 'health'],
      recipients: ['friend', 'family'],
      scenes: ['birthday'],
      season: '10〜11月',
      description: '秋に咲く紫の花で、赤いめしべが香辛料になります。',
      origin: '古くから薬や染料、香辛料として人々に喜びをもたらしてきたことから「歓喜」といわれます。',
      trivia: '乾燥させためしべが「サフラン」というスパイスです。1輪から少ししか採れないため、とても高価です。',
      message: '小さな楽しみが、毎日を明るく彩ります。',
      point: '「歓喜」「陽気」。明るいお祝いに。',
      look: { shape: 'cup', colors: ['#b79ae6', '#8c68cf', '#e2432f'] }
    },
    {
      id: 'peony', name: 'シャクヤク', kana: 'しゃくやく', emoji: '🌸',
      meanings: ['はにかみ', '誠実', '幸せな結婚'],
      categories: ['love', 'happiness', 'sincerity'],
      recipients: ['partner', 'special', 'parents'],
      scenes: ['wedding', 'proposal', 'mothersday', 'anniversary'],
      season: '5〜6月',
      description: 'ふんわりとした大輪の花が豪華で愛らしい花です。',
      origin: '夕方になると花を閉じる様子が恥じらっているように見えることから「はにかみ」といわれます。',
      trivia: '「立てば芍薬、座れば牡丹、歩く姿は百合の花」と美しい人のたとえに使われます。根は漢方薬にもなります。',
      message: 'ちょっと照れくさい気持ちも、とても大切な宝物。',
      point: '「幸せな結婚」。華やかなお祝いの花束に。',
      look: { shape: 'layered', colors: ['#fbc3cf', '#f1899f', '#f4c95d'] }
    },
    {
      id: 'aster', name: 'シオン', kana: 'しおん', emoji: '💜',
      meanings: ['君を忘れない', '追憶', '遠方にある人を思う'],
      categories: ['comfort', 'friendship'],
      recipients: ['friend', 'special'],
      scenes: ['farewell'],
      season: '9〜10月',
      description: '秋に淡い紫の小花を咲かせる、背の高い花です。',
      origin: '古典『今昔物語集』に、亡き父を忘れないために紫苑を植えた兄弟の話があり、「君を忘れない」の花言葉につながっています。',
      trivia: '平安時代から親しまれてきた花で、「思い草」とも呼ばれました。',
      message: '会えない時間も、想いはちゃんと届いています。',
      point: '「君を忘れない」。遠くへ行く大切な人に。',
      look: { shape: 'daisy', colors: ['#c9b8ec', '#a48ed9', '#f2cf55'] }
    },
    {
      id: 'daphne', name: 'ジンチョウゲ', kana: 'じんちょうげ', emoji: '🌸',
      meanings: ['栄光', '不滅', '永遠'],
      categories: ['respect', 'health', 'future'],
      recipients: ['teacher', 'boss', 'parents'],
      scenes: ['graduation', 'farewell'],
      season: '2〜4月',
      description: '早春に甘く強い香りを漂わせる、小さな花の木です。',
      origin: '葉が一年中緑を保ち、香りが遠くまで届くことから「不滅」「永遠」、その気高さから「栄光」といわれます。',
      trivia: '香木の「沈香」と、スパイスの「丁子（クローブ）」の香りにたとえて名づけられました。三大香木のひとつです。',
      message: 'これまでの歩みは、ずっとあなたの誇りです。',
      point: '「栄光」。がんばりを称えたい人へ。',
      look: { shape: 'cluster', colors: ['#f7c6d7', '#e894b3', '#fbf1f5'] }
    },
    {
      id: 'sweet-pea', name: 'スイートピー', kana: 'すいーとぴー', emoji: '🦋',
      meanings: ['門出', '優しい思い出', 'ほのかな喜び'],
      categories: ['future', 'comfort', 'kindness'],
      recipients: ['friend', 'teacher', 'boss'],
      scenes: ['graduation', 'farewell', 'entrance'],
      season: '12〜4月（切り花）',
      description: 'ひらひらと軽やかな花びらと、甘い香りが魅力の花です。',
      origin: '蝶が今にも飛び立とうとしているような花の形から、「門出」の花言葉が生まれました。',
      trivia: 'やわらかなパステルカラーが多く、卒業や送別の花束によく使われます。',
      message: '旅立ちの日は、やさしい思い出と一緒に。',
      point: '「門出」。卒業や送別の定番の花。',
      look: { shape: 'round', colors: ['#f6c3e0', '#dc9ad0', '#f8e7f0'] }
    },
    {
      id: 'lily-of-the-valley', name: 'スズラン', kana: 'すずらん', emoji: '🔔',
      meanings: ['再び幸せが訪れる', '純粋', '謙遜'],
      categories: ['happiness', 'hope', 'kindness'],
      recipients: ['family', 'friend', 'special'],
      scenes: ['wedding', 'birthday', 'thanks'],
      season: '4〜6月',
      description: '鈴のような白い花がうつむいて並ぶ、清らかな花です。',
      origin: 'ヨーロッパでは春の訪れを告げる花として親しまれ、そこから「再び幸せが訪れる」といわれます。',
      trivia: 'フランスでは5月1日に大切な人へスズランを贈る習慣があります。全草に毒があるので、小さな子やペットのいる場所では注意しましょう。',
      message: 'また笑える日が、ちゃんとやってきます。',
      point: '「再び幸せが訪れる」。幸せを願う贈り物に。',
      look: { shape: 'bell', colors: ['#ffffff', '#e8efe4', '#8dbb84'] }
    },
    {
      id: 'snowdrop', name: 'スノードロップ', kana: 'すのーどろっぷ', emoji: '🤍',
      meanings: ['希望', '慰め'],
      categories: ['hope', 'comfort'],
      recipients: ['friend', 'special'],
      scenes: ['cheer'],
      season: '2〜3月',
      description: '雪どけのころ、白いしずくのような花を咲かせる球根植物です。',
      origin: 'エデンの園を追われたイヴを天使が慰め、降る雪をこの花に変えたという言い伝えから「希望」「慰め」といわれます。',
      trivia: '寒さにとても強く、雪の中から顔を出すように咲きます。ヨーロッパでは春を告げる花として知られています。',
      message: '冷たい季節の中にも、小さな光は咲いています。',
      point: '「希望」「慰め」。静かに励ましたいときに。',
      look: { shape: 'bell', colors: ['#ffffff', '#e5ebf0', '#9cc59a'] }
    },
    {
      id: 'violet', name: 'スミレ', kana: 'すみれ', emoji: '💜',
      meanings: ['謙虚', '誠実', '小さな幸せ'],
      colorMeanings: [
        { color: '紫', hex: '#8c6ad6', meanings: ['貞節', '愛'] },
        { color: '白', hex: '#f6f3ee', meanings: ['あどけない恋', '無邪気な恋'] },
        { color: '黄', hex: '#f3d56b', meanings: ['つつましい喜び', '田園の幸福'] }
      ],
      categories: ['sincerity', 'happiness', 'kindness'],
      recipients: ['friend', 'family', 'child'],
      scenes: ['thanks'],
      season: '3〜5月',
      description: '道ばたにも咲く、小さくて可憐な春の花です。',
      origin: '野原で目立たず控えめに咲く姿から「謙虚」「誠実」といわれます。',
      trivia: '花の形が大工道具の「墨入れ（墨壺）」に似ていることが名前の由来という説があります。',
      message: '控えめな優しさこそ、長く心に残ります。',
      point: '「小さな幸せ」。さりげない気持ちを伝えたいときに。',
      look: { shape: 'round', colors: ['#a88be0', '#7d5bc8', '#f4d45c'] }
    },
    {
      id: 'statice', name: 'スターチス', kana: 'すたーちす', emoji: '💜',
      meanings: ['変わらぬ心', '途絶えぬ記憶'],
      categories: ['sincerity', 'friendship', 'comfort'],
      recipients: ['friend', 'family', 'teacher'],
      scenes: ['graduation', 'farewell', 'anniversary'],
      season: '4〜6月（切り花は通年）',
      description: 'カサカサとした質感の、色あせにくい花です。',
      origin: 'ドライフラワーにしても色や形がほとんど変わらないことから「変わらぬ心」「途絶えぬ記憶」といわれます。',
      trivia: '色づいて見える部分はがくで、本当の花はその中の小さな白い部分です。',
      message: '変わらないものがあるから、前へ進めます。',
      point: '「変わらぬ心」。卒業や記念の花束に。',
      look: { shape: 'cluster', colors: ['#c4b2ee', '#9a80dc', '#ffffff'] }
    },
    {
      id: 'globe-amaranth', name: 'センニチコウ', kana: 'せんにちこう', emoji: '🔴',
      meanings: ['色あせぬ愛', '変わらぬ愛情', '不朽'],
      categories: ['love', 'health', 'sincerity'],
      recipients: ['parents', 'partner', 'family'],
      scenes: ['anniversary', 'thanks'],
      season: '5〜11月',
      description: 'ころんとした丸い花が長く咲き続ける、かわいらしい花です。',
      origin: '夏から秋まで長く咲き、乾燥させても色が残ることから「色あせぬ愛」「不朽」といわれます。',
      trivia: '「千日紅」の名前は、千日も色あせないほど長く楽しめることに由来します。',
      message: '長く続く想いは、何よりの贈り物です。',
      point: '「変わらぬ愛情」。長く元気でいてほしい人に。',
      look: { shape: 'cluster', colors: ['#ef7fa6', '#d44d80', '#f5b3ca'] }
    },
    {
      id: 'dahlia', name: 'ダリア', kana: 'だりあ', emoji: '🌺',
      meanings: ['華麗', '優雅', '感謝'],
      categories: ['thanks', 'respect', 'happiness'],
      recipients: ['boss', 'teacher', 'parents', 'special'],
      scenes: ['thanks', 'birthday', 'farewell'],
      season: '6〜11月',
      description: '幾重にも重なる花びらが豪華な、存在感のある花です。',
      origin: 'フランス革命のころ、ナポレオン皇后ジョセフィーヌが愛した花として知られ、その華やかさから「華麗」「優雅」といわれます。',
      trivia: 'メキシコの国花です。日本では「天竺牡丹（てんじくぼたん）」とも呼ばれました。',
      message: '感謝を伝える日は、少しだけ華やかに。',
      point: '「感謝」「華麗」。お世話になった人へ。',
      look: { shape: 'layered', colors: ['#f7a1b2', '#e0607f', '#c94667'] }
    },
    {
      id: 'dandelion', name: 'タンポポ', kana: 'たんぽぽ', emoji: '🌼',
      meanings: ['真心の愛', '幸せ', '神託'],
      categories: ['love', 'happiness', 'hope'],
      recipients: ['child', 'friend', 'family'],
      scenes: ['cheer'],
      season: '3〜5月',
      description: '春の野原に明るい黄色を添える、身近な花です。',
      origin: 'ヨーロッパで綿毛を吹いて恋や未来を占ったことから「神託」、明るい花の姿から「幸せ」といわれます。',
      trivia: '日本在来のタンポポと、外来のセイヨウタンポポがあり、花の下の「総苞片」が反り返っているのがセイヨウタンポポです。',
      message: 'どこにいても、自分の場所で咲けばいい。',
      point: '「幸せ」「真心の愛」。子どもにも身近な花。',
      look: { shape: 'daisy', colors: ['#fbe07a', '#f2c23c', '#e0a52a'] }
    },
    {
      id: 'tulip', name: 'チューリップ', kana: 'ちゅーりっぷ', emoji: '🌷',
      meanings: ['思いやり'],
      colorMeanings: [
        { color: '赤', hex: '#e2566a', meanings: ['愛の告白', '真実の愛'] },
        { color: 'ピンク', hex: '#f5a6bf', meanings: ['愛の芽生え', '誠実な愛'] },
        { color: '白', hex: '#f6f3ee', meanings: ['新しい愛', '純粋'] },
        { color: '紫', hex: '#9a78dc', meanings: ['不滅の愛', '気高さ'] },
        { color: 'オレンジ', hex: '#f5a067', meanings: ['照れ屋'] },
        { color: '黄', hex: '#f3d56b', meanings: ['名声', '望みのない恋'], note: '恋愛の贈り物では避けられることがあります' }
      ],
      categories: ['love', 'kindness', 'hope'],
      recipients: ['partner', 'friend', 'child', 'special'],
      scenes: ['confession', 'entrance', 'birthday', 'visit'],
      season: '3〜5月',
      description: '丸みのある花がかわいらしい、春の代表的な球根植物です。',
      origin: '色ごとに多彩な花言葉があり、特に赤は情熱的な色から「愛の告白」といわれます。',
      trivia: '17世紀のオランダでは球根の値段が高騰し、「チューリップ・バブル」と呼ばれる騒動が起きました。',
      message: '思いやりは、いちばんやさしい魔法です。',
      point: '赤は「愛の告白」。色で想いを伝えられる花。',
      look: { shape: 'cup', colors: ['#f7889c', '#e25574', '#8dbb84'] }
    },
    {
      id: 'camellia', name: 'ツバキ', kana: 'つばき', emoji: '🌺',
      meanings: ['控えめな優しさ', '誇り'],
      colorMeanings: [
        { color: '赤', hex: '#d8425d', meanings: ['控えめな素晴らしさ', '気取らない優美さ'] },
        { color: '白', hex: '#f6f3ee', meanings: ['完全なる美しさ', '至上の愛らしさ'] },
        { color: 'ピンク', hex: '#f5a6bf', meanings: ['控えめな美'] }
      ],
      categories: ['kindness', 'respect'],
      recipients: ['parents', 'teacher'],
      scenes: ['thanks'],
      season: '12〜4月',
      description: 'つややかな葉と、凛とした花が美しい日本の花木です。',
      origin: '香りが控えめで、つややかな葉に包まれて静かに咲く姿から「控えめな優しさ」といわれます。',
      trivia: '花が首から落ちるように散るため、お見舞いには避けられることがあります。種からとれる椿油は髪の手入れに使われてきました。',
      message: '目立たなくても、あなたの優しさは伝わっています。',
      point: '「控えめな優しさ」。奥ゆかしい感謝の気持ちに。',
      look: { shape: 'round', colors: ['#e8657c', '#c93a57', '#f4d15a'] }
    },
    {
      id: 'daisy', name: 'デイジー', kana: 'でいじー', emoji: '🌼',
      meanings: ['平和', '希望', '純潔', '美人'],
      categories: ['hope', 'kindness', 'happiness'],
      recipients: ['child', 'friend', 'family'],
      scenes: ['birth', 'birthday', 'entrance'],
      season: '3〜5月',
      description: '丸くかわいらしい花が集まって咲く、春の花（ヒナギク）です。',
      origin: '明るく素朴な花の姿から「平和」「希望」といわれます。',
      trivia: '朝に開いて夜に閉じることから「day\'s eye（太陽の目）」が名前の由来といわれます。',
      message: '朝がくるたび、希望はまた開きます。',
      point: '「希望」「平和」。子どもの成長を願う花に。',
      look: { shape: 'daisy', colors: ['#ffffff', '#f7d5de', '#f2c94c'] }
    },
    {
      id: 'lisianthus', name: 'トルコキキョウ', kana: 'とるこききょう', emoji: '💜',
      meanings: ['優美', 'すがすがしい美しさ', '希望'],
      colorMeanings: [
        { color: '紫', hex: '#9a78dc', meanings: ['希望'] },
        { color: '白', hex: '#f6f3ee', meanings: ['思いやり'] },
        { color: 'ピンク', hex: '#f5a6bf', meanings: ['優美'] }
      ],
      categories: ['hope', 'thanks', 'kindness'],
      recipients: ['parents', 'teacher', 'boss', 'family'],
      scenes: ['thanks', 'wedding', 'farewell', 'mothersday'],
      season: '6〜9月',
      description: 'バラのようにふんわり咲く品種もある、上品な花です。',
      origin: 'やわらかな花びらとすっきりした花姿から「優美」「すがすがしい美しさ」といわれます。',
      trivia: '名前に反してトルコ原産でもキキョウの仲間でもなく、北アメリカ原産のリンドウの仲間です。',
      message: 'すがすがしい気持ちで、今日を始めましょう。',
      point: '「優美」「希望」。感謝の花束の名脇役に。',
      look: { shape: 'layered', colors: ['#c9b3ee', '#9a78dc', '#e9dff8'] }
    },
    {
      id: 'dianthus', name: 'ナデシコ', kana: 'なでしこ', emoji: '🌸',
      meanings: ['純愛', '無邪気', '大胆'],
      categories: ['love', 'kindness'],
      recipients: ['partner', 'child', 'special'],
      scenes: ['confession', 'birthday'],
      season: '5〜8月',
      description: '細かな切れ込みのある花びらが可憐な、秋の七草のひとつです。',
      origin: '可憐でけなげな花の姿から「純愛」「無邪気」といわれます。',
      trivia: '「撫でし子」、つまり撫でたいほどかわいい子という意味が名前の由来とされます。',
      message: 'まっすぐな気持ちは、いつだって美しい。',
      point: '「純愛」。ひたむきな想いを伝えたいときに。',
      look: { shape: 'star', colors: ['#f7a9c6', '#e5739e', '#fbe1eb'] }
    },
    {
      id: 'rape-blossom', name: 'ナノハナ', kana: 'なのはな', emoji: '🌼',
      meanings: ['快活な愛', '小さな幸せ', '競争'],
      categories: ['happiness', 'cheer', 'hope'],
      recipients: ['friend', 'child', 'family'],
      scenes: ['entrance', 'cheer'],
      season: '2〜4月',
      description: '一面を黄色に染める、明るい春の花です。',
      origin: '小さな黄色い花がたくさん集まって明るく咲く様子から「小さな幸せ」「快活な愛」といわれます。',
      trivia: 'アブラナ科の花の総称で、種から菜種油がとれます。つぼみは春の食材としても親しまれています。',
      message: '明るい色は、心まであたためてくれます。',
      point: '「小さな幸せ」。春のはじまりを一緒に喜びたい人に。',
      look: { shape: 'cluster', colors: ['#fbe47a', '#f2c33c', '#9cc57a'] }
    },
    {
      id: 'nemophila', name: 'ネモフィラ', kana: 'ねもふぃら', emoji: '💙',
      meanings: ['どこでも成功', '可憐', 'あなたを許す'],
      categories: ['cheer', 'future', 'kindness'],
      recipients: ['friend', 'child'],
      scenes: ['entrance', 'cheer', 'graduation'],
      season: '4〜5月',
      description: '空色の小さな花が一面に広がる、春の花です。',
      origin: 'どんな場所でもよく育ち、一面に花を咲かせる強さから「どこでも成功」といわれます。',
      trivia: '北アメリカ原産で、「ベビーブルーアイズ」という英名もあります。',
      message: 'どこへ行っても、あなたはきっと大丈夫。',
      point: '「どこでも成功」。新しい環境へ進む人に。',
      look: { shape: 'round', colors: ['#a9d2f3', '#6fb0e6', '#ffffff'] }
    },
    {
      id: 'hibiscus', name: 'ハイビスカス', kana: 'はいびすかす', emoji: '🌺',
      meanings: ['繊細な美', '新しい恋', '勇敢'],
      categories: ['love', 'cheer'],
      recipients: ['partner', 'friend'],
      scenes: ['confession', 'cheer', 'birthday'],
      season: '5〜10月',
      description: '南国を思わせる、大きく鮮やかな花です。',
      origin: '朝に咲いて夕方にはしぼむ一日花であることから「繊細な美」、鮮やかな色から「勇敢」といわれます。',
      trivia: 'ハワイ州の花として知られています。一輪の命は短いですが、次々と新しいつぼみが咲いていきます。',
      message: '今日という一日を、思いきり咲かせましょう。',
      point: '「新しい恋」「勇敢」。夏のエールに。',
      look: { shape: 'round', colors: ['#f7746f', '#e04356', '#f7d55c'] }
    },
    {
      id: 'dogwood', name: 'ハナミズキ', kana: 'はなみずき', emoji: '🌸',
      meanings: ['返礼', '私の想いを受けてください', '永続性'],
      categories: ['thanks', 'love', 'friendship'],
      recipients: ['partner', 'friend', 'special'],
      scenes: ['thanks', 'confession'],
      season: '4〜5月',
      description: '街路樹としてもおなじみの、春に咲く花木です。',
      origin: '日本がアメリカに桜を贈ったお礼として、ハナミズキが贈られた歴史から「返礼」といわれます。',
      trivia: '1912年に東京市からワシントンへ桜が贈られ、その返礼として1915年に日本へハナミズキが届きました。花びらに見えるのは総苞です。',
      message: 'もらった優しさは、次の誰かへつないでいけます。',
      point: '「返礼」。お礼の気持ちを伝えたいときに。',
      look: { shape: 'round', colors: ['#fbe2e8', '#f2aabd', '#a9c88a'] }
    },
    {
      id: 'ornamental-cabbage', name: 'ハボタン', kana: 'はぼたん', emoji: '🥬',
      meanings: ['祝福', '慈愛', '利益'],
      categories: ['happiness', 'kindness'],
      recipients: ['family', 'parents'],
      scenes: ['birthday', 'thanks'],
      season: '11〜3月（観賞期）',
      description: '葉が花のように重なる、冬の寄せ植えの主役です。',
      origin: 'お正月飾りなど、おめでたい場面に使われてきたことから「祝福」といわれます。',
      trivia: 'キャベツの仲間で、寒さに当たることで中心の葉が白やピンクに色づきます。',
      message: '寒い季節も、あなたの周りは祝福でいっぱいです。',
      point: '「祝福」。冬のお祝いや新年の贈り物に。',
      look: { shape: 'layered', colors: ['#e7d4ee', '#b58fc9', '#8fb58a'] }
    },
    {
      id: 'rose', name: 'バラ', kana: 'ばら', emoji: '🌹',
      meanings: ['愛', '美'],
      colorMeanings: [
        { color: '赤', hex: '#d8425d', meanings: ['あなたを愛しています', '愛情', '情熱'] },
        { color: '白', hex: '#f6f3ee', meanings: ['純潔', '尊敬'] },
        { color: 'ピンク', hex: '#f5a6bf', meanings: ['感謝', '上品', 'しとやか'] },
        { color: 'オレンジ', hex: '#f5a067', meanings: ['絆', '信頼'] },
        { color: '青', hex: '#8fa9e8', meanings: ['夢かなう', '奇跡'] },
        { color: '黄', hex: '#f3d56b', meanings: ['友情', '嫉妬'], note: '日本の父の日のシンボルカラーでもあります' }
      ],
      categories: ['love', 'respect', 'thanks', 'happiness'],
      recipients: ['partner', 'special', 'parents', 'friend'],
      scenes: ['proposal', 'confession', 'anniversary', 'birthday', 'wedding', 'fathersday', 'mothersday'],
      season: '5〜6月、10〜11月',
      description: '「花の女王」と呼ばれる、愛の象徴の花です。',
      origin: '古代ギリシャ・ローマの時代から愛と美の女神と結びつけられてきたことから、「愛」「美」の花言葉があります。',
      trivia: '贈る本数によっても意味が変わるといわれ、3本は「愛しています」、108本は「結婚してください」とされます。',
      message: '愛しているという言葉を、花が代わりに伝えます。',
      point: '赤は「愛情」、ピンクは「感謝」。想いに合わせて色を選べます。',
      look: { shape: 'layered', colors: ['#f07c8f', '#d8425d', '#b52e4b'] }
    },
    {
      id: 'pansy', name: 'パンジー', kana: 'ぱんじー', emoji: '💜',
      meanings: ['もの思い', '私を思って'],
      colorMeanings: [
        { color: '紫', hex: '#8c6ad6', meanings: ['思慮深い'] },
        { color: '黄', hex: '#f3d56b', meanings: ['つつましい幸せ'] },
        { color: '白', hex: '#f6f3ee', meanings: ['温順'] }
      ],
      categories: ['love', 'comfort'],
      recipients: ['partner', 'friend', 'special'],
      scenes: ['confession'],
      season: '10〜5月',
      description: '人の顔のような模様が愛らしい、秋から春の花です。',
      origin: '花の模様が、うつむいて考えごとをする人の顔のように見えることから「もの思い」といわれます。',
      trivia: '名前はフランス語で「思考」を意味する「パンセ（pensée）」に由来します。',
      message: 'ふと思い出す人がいるのは、幸せなことです。',
      point: '「私を思って」。会いたい人に。',
      look: { shape: 'round', colors: ['#b595e6', '#7a55c7', '#f5d55c'] }
    },
    {
      id: 'red-spider-lily', name: 'ヒガンバナ', kana: 'ひがんばな', emoji: '🌺',
      meanings: ['情熱', '再会', 'また会う日を楽しみに'],
      categories: ['comfort', 'love'],
      recipients: [],
      scenes: [],
      season: '9月',
      description: '秋のお彼岸のころ、燃えるような赤い花を咲かせます。',
      origin: '花が咲く時期には葉がなく、花と葉が互いに会えないことから「再会」「また会う日を楽しみに」といわれます。',
      trivia: '球根に毒があり、田んぼのあぜ道などに植えられてきました。お墓の近くに咲くことも多く、贈り物には選ばれにくい花です。',
      message: 'また会える日を楽しみに、今日を過ごしましょう。',
      point: '「再会」。贈り物より、観賞で楽しみたい花。',
      look: { shape: 'spike', colors: ['#ef5a5e', '#c93043', '#f57d7a'] }
    },
    {
      id: 'hyacinth', name: 'ヒヤシンス', kana: 'ひやしんす', emoji: '💜',
      meanings: ['スポーツ', 'ゲーム', '悲哀'],
      colorMeanings: [
        { color: '青', hex: '#8fa9e8', meanings: ['変わらぬ愛'] },
        { color: '白', hex: '#f6f3ee', meanings: ['控えめな愛らしさ'] },
        { color: 'ピンク', hex: '#f5a6bf', meanings: ['しとやかなかわいらしさ'] },
        { color: '紫', hex: '#9a78dc', meanings: ['初恋のひたむきさ', '悲しみ'] }
      ],
      categories: ['love', 'cheer'],
      recipients: ['partner', 'friend'],
      scenes: ['cheer'],
      season: '3〜4月',
      description: '甘い香りの小花が穂のように集まって咲く球根植物です。',
      origin: 'ギリシャ神話で、円盤投げをしていた青年ヒュアキントスの血から咲いた花とされ、「スポーツ」「悲哀」の花言葉につながりました。',
      trivia: '球根を水につけて育てる「水栽培」でも親しまれています。',
      message: '夢中になれるものがある毎日は、宝物です。',
      point: '青は「変わらぬ愛」。スポーツをがんばる人の応援にも。',
      look: { shape: 'spike', colors: ['#b8a4ec', '#8a6fd8', '#d9cef5'] }
    },
    {
      id: 'sunflower', name: 'ひまわり', kana: 'ひまわり', emoji: '🌻',
      meanings: ['あなただけを見つめる', '憧れ', 'あなたは素晴らしい'],
      categories: ['love', 'respect', 'cheer', 'happiness'],
      recipients: ['partner', 'parents', 'friend', 'child', 'special'],
      scenes: ['fathersday', 'birthday', 'cheer', 'visit', 'confession'],
      season: '7〜9月',
      description: '太陽のように明るい、夏を代表する大きな花です。',
      origin: '太陽の動きを追うように花が向きを変えると考えられていたことから「あなただけを見つめる」といわれます。',
      trivia: '実際に太陽を追うのはつぼみの時期までで、花が開くとほぼ東を向いたまま止まります。',
      message: 'あなたの笑顔は、誰かの太陽になっています。',
      point: '「あなたは素晴らしい」。父の日や応援に。',
      look: { shape: 'daisy', colors: ['#fcd54d', '#f5b52c', '#7a4a24'] }
    },
    {
      id: 'viola', name: 'ビオラ', kana: 'びおら', emoji: '💜',
      meanings: ['誠実な愛', '信頼', '少女の恋'],
      categories: ['love', 'sincerity', 'friendship'],
      recipients: ['partner', 'friend', 'child'],
      scenes: ['anniversary', 'confession'],
      season: '10〜5月',
      description: 'パンジーより小ぶりな花を、たくさん咲かせる花です。',
      origin: '小さな花が次々と長く咲き続けるけなげな姿から「誠実な愛」「信頼」といわれます。',
      trivia: 'パンジーとの違いは主に花の大きさで、一般に小輪のものがビオラと呼ばれます。花は食用（エディブルフラワー）にもなります。',
      message: '信じてくれる人がいるから、がんばれます。',
      point: '「信頼」。長いつきあいの人へ。',
      look: { shape: 'round', colors: ['#c8b0f0', '#9571d9', '#f7d962'] }
    },
    {
      id: 'wisteria', name: 'フジ', kana: 'ふじ', emoji: '💜',
      meanings: ['優しさ', '歓迎', '決して離れない'],
      categories: ['kindness', 'love', 'friendship'],
      recipients: ['partner', 'family', 'friend'],
      scenes: ['wedding', 'anniversary'],
      season: '4〜5月',
      description: '紫の花房がしだれて咲く、日本の春の花木です。',
      origin: 'しなやかに垂れる花房のやさしい姿から「優しさ」、つるがしっかり絡みつくことから「決して離れない」といわれます。',
      trivia: '藤棚の花房は長いものでは1メートルを超えることもあります。古くから和歌にも詠まれてきました。',
      message: 'やさしさは、そっと垂れる花のように届きます。',
      point: '「決して離れない」。長く寄り添いたい人に。',
      look: { shape: 'spike', colors: ['#c6b1ee', '#9d82dd', '#e5dbf8'] }
    },
    {
      id: 'freesia', name: 'フリージア', kana: 'ふりーじあ', emoji: '💛',
      meanings: ['あどけなさ', '親愛の情'],
      colorMeanings: [
        { color: '黄', hex: '#f3d56b', meanings: ['無邪気'] },
        { color: '白', hex: '#f6f3ee', meanings: ['あどけなさ'] },
        { color: '赤', hex: '#e2566a', meanings: ['純潔'] },
        { color: '紫', hex: '#9a78dc', meanings: ['憧れ'] },
        { color: 'ピンク', hex: '#f5a6bf', meanings: ['感謝'] }
      ],
      categories: ['thanks', 'friendship', 'kindness'],
      recipients: ['friend', 'family', 'child', 'teacher'],
      scenes: ['thanks', 'graduation', 'birthday'],
      season: '3〜4月',
      description: '甘くさわやかな香りが魅力の、春の球根植物です。',
      origin: '発見した植物学者が、友人の名前をこの花につけたという逸話から「親愛の情」といわれます。',
      trivia: '名前はドイツの医師フレーゼの名にちなみます。香りのよさで人気の切り花です。',
      message: '親しい人への「ありがとう」は、何度言ってもいい。',
      point: 'ピンクは「感謝」。親しい人へのお礼に。',
      look: { shape: 'trumpet', colors: ['#fbe07a', '#f2c23c', '#fff6d2'] }
    },
    {
      id: 'blue-star', name: 'ブルースター', kana: 'ぶるーすたー', emoji: '💙',
      meanings: ['信じあう心', '幸福な愛'],
      categories: ['love', 'happiness', 'sincerity'],
      recipients: ['partner', 'child', 'special'],
      scenes: ['wedding', 'birth', 'anniversary'],
      season: '5〜10月',
      description: '水色の星形の花が、さわやかでかわいらしい花です。',
      origin: '澄んだ青い花の色が、誠実さや信頼を思わせることから「信じあう心」といわれます。',
      trivia: '花嫁が身につけると幸せになる「サムシングブルー」として、ブーケによく使われます。男の子の誕生祝いにも人気です。',
      message: '信じあえる人がいることが、いちばんの幸せ。',
      point: '「幸福な愛」。結婚祝いや出産祝いに。',
      look: { shape: 'star', colors: ['#a9cff0', '#6aa8df', '#e8f3fb'] }
    },
    {
      id: 'tree-peony', name: 'ボタン', kana: 'ぼたん', emoji: '🌸',
      meanings: ['風格', '富貴', '王者の風格'],
      categories: ['respect', 'happiness', 'health'],
      recipients: ['parents', 'boss', 'teacher'],
      scenes: ['thanks', 'birthday'],
      season: '4〜5月',
      description: '大きく豪華な花を咲かせる、「百花の王」と呼ばれる花木です。',
      origin: '中国で「花の王」として愛され、その堂々とした大輪の姿から「風格」「富貴」といわれます。',
      trivia: 'シャクヤクによく似ていますが、ボタンは冬も枝が残る木で、シャクヤクは冬に地上部が枯れる草です。',
      message: 'あなたの歩んできた道が、その風格をつくっています。',
      point: '「風格」。尊敬する目上の方に。',
      look: { shape: 'layered', colors: ['#f7b3c4', '#e87b97', '#f3cf5c'] }
    },
    {
      id: 'poinsettia', name: 'ポインセチア', kana: 'ぽいんせちあ', emoji: '🎄',
      meanings: ['祝福する', '聖夜', '私の心は燃えている'],
      categories: ['happiness', 'love'],
      recipients: ['family', 'partner', 'friend'],
      scenes: ['birthday', 'anniversary'],
      season: '11〜12月（観賞期）',
      description: '赤と緑がクリスマスを思わせる、冬の鉢花です。',
      origin: '赤・緑・白のクリスマスカラーがそろう姿から「祝福する」「聖夜」といわれます。',
      trivia: '赤く色づいているのは花ではなく「苞（ほう）」という葉です。中心の小さな粒が本当の花です。',
      message: '今年もよくがんばったあなたに、祝福を。',
      point: '「祝福する」。冬のお祝いに。',
      look: { shape: 'star', colors: ['#e8475a', '#c22c43', '#e9d05a'] }
    },
    {
      id: 'poppy', name: 'ポピー', kana: 'ぽぴー', emoji: '🌺',
      meanings: ['いたわり', '思いやり', '恋の予感'],
      categories: ['kindness', 'comfort', 'love'],
      recipients: ['friend', 'family', 'special'],
      scenes: ['visit', 'confession'],
      season: '4〜6月',
      description: '薄紙のような花びらが風にゆれる、春の花です。',
      origin: 'やわらかく繊細な花びらが、人をいたわるようなやさしさを感じさせることから「いたわり」「思いやり」といわれます。',
      trivia: '和名はヒナゲシ（雛罌粟）。中国の故事にちなみ「虞美人草」とも呼ばれます。',
      message: 'がんばりすぎず、今日は自分をいたわって。',
      point: '「いたわり」。やさしく気づかいたい人へ。',
      look: { shape: 'cup', colors: ['#f89a86', '#ec6a5d', '#3a3440'] }
    },
    {
      id: 'marguerite', name: 'マーガレット', kana: 'まーがれっと', emoji: '🌼',
      meanings: ['恋占い', '真実の愛', '信頼'],
      categories: ['love', 'friendship', 'sincerity'],
      recipients: ['partner', 'friend', 'special'],
      scenes: ['confession', 'birthday', 'visit'],
      season: '3〜6月',
      description: '白い花びらと黄色い中心がさわやかな、春の花です。',
      origin: '花びらを1枚ずつ摘んで「好き・嫌い」と恋を占う花占いに使われたことから「恋占い」といわれます。',
      trivia: 'カナリア諸島原産で、和名は「モクシュンギク（木春菊）」です。',
      message: '信じる気持ちは、どんな占いより確かです。',
      point: '「信頼」「真実の愛」。親しみをこめて。',
      look: { shape: 'daisy', colors: ['#ffffff', '#f3eee6', '#f2c94c'] }
    },
    {
      id: 'marigold', name: 'マリーゴールド', kana: 'まりーごーるど', emoji: '🧡',
      meanings: ['変わらぬ愛', '勇者', '嫉妬'],
      categories: ['cheer', 'love'],
      recipients: ['friend', 'family'],
      scenes: ['cheer'],
      season: '5〜11月',
      description: '明るいオレンジや黄色の花が長く咲く、元気な印象の花です。',
      origin: '長い期間咲き続ける強さから「変わらぬ愛」「勇者」、一方で鮮やかな黄色から「嫉妬」ともいわれます。',
      trivia: '聖母マリアの祭日のころに咲くことから「マリアの黄金の花」が名前の由来です。野菜の近くに植える「コンパニオンプランツ」としても知られます。',
      message: '強さとは、毎日を咲かせ続けること。',
      point: '「勇者」。挑戦する人を明るく応援。',
      look: { shape: 'layered', colors: ['#fbbd5a', '#f39a2c', '#e07b1c'] }
    },
    {
      id: 'mimosa', name: 'ミモザ', kana: 'みもざ', emoji: '💛',
      meanings: ['感謝', '友情', '優雅', '秘密の恋'],
      categories: ['thanks', 'friendship', 'happiness'],
      recipients: ['friend', 'family', 'parents', 'boss', 'teacher'],
      scenes: ['thanks', 'birthday', 'farewell'],
      season: '2〜4月',
      description: 'ふわふわの黄色い花が、春の光のように咲く木です。',
      origin: 'イタリアでは3月8日の「女性の日」に、日ごろの感謝をこめて男性から女性へミモザを贈る習慣があり、「感謝」の花言葉につながっています。',
      trivia: '日本で「ミモザ」と呼ばれるのは、主にギンヨウアカシアなどのアカシアの仲間です。',
      message: 'ふわりと明るい気持ちで、ありがとうを。',
      point: '「感謝」「友情」。女性の日や送別にも。',
      look: { shape: 'cluster', colors: ['#fbe66a', '#f3cf2e', '#a9c98a'] }
    },
    {
      id: 'muscari', name: 'ムスカリ', kana: 'むすかり', emoji: '💙',
      meanings: ['通じ合う心', '明るい未来'],
      categories: ['future', 'friendship', 'hope'],
      recipients: ['friend', 'partner', 'child'],
      scenes: ['entrance', 'graduation', 'anniversary'],
      season: '3〜4月',
      description: '青紫の小さな粒のような花が集まって咲く球根植物です。',
      origin: '小さな花がぎゅっと寄り添って咲く姿から「通じ合う心」、春の青空のような色から「明るい未来」といわれます。',
      trivia: 'ブドウの房のような姿から「グレープヒヤシンス」とも呼ばれます。',
      message: '言葉にしなくても、伝わっていることがあります。',
      point: '「明るい未来」。新生活を始める人に。',
      look: { shape: 'spike', colors: ['#8ea2e6', '#5f74cf', '#c9d2f5'] }
    },
    {
      id: 'lily', name: 'ユリ', kana: 'ゆり', emoji: '🤍',
      meanings: ['純粋', '威厳', '無垢'],
      colorMeanings: [
        { color: '白', hex: '#f6f3ee', meanings: ['純潔', '威厳'] },
        { color: 'オレンジ', hex: '#f5a067', meanings: ['華麗', '愉快'] },
        { color: '黄', hex: '#f3d56b', meanings: ['陽気', '偽り'] }
      ],
      categories: ['respect', 'sincerity', 'happiness'],
      recipients: ['parents', 'boss', 'special'],
      scenes: ['wedding', 'fathersday', 'mothersday', 'thanks'],
      season: '6〜8月',
      description: '大きく気品ある花と、豊かな香りをもつ花です。',
      origin: 'キリスト教で白いユリが聖母マリアの象徴とされたことから「純粋」「無垢」といわれます。',
      trivia: '花粉が服につくと落ちにくいため、飾るときは開花したらおしべを取り除くのがおすすめです。香りが強いのでお見舞いでは控えることがあります。',
      message: '清らかな心は、それだけで人を惹きつけます。',
      point: '「威厳」「純粋」。敬意を込めた贈り物に。',
      look: { shape: 'star', colors: ['#fdfaf3', '#ece3d3', '#e4a64a'] }
    },
    {
      id: 'lilac', name: 'ライラック', kana: 'らいらっく', emoji: '💜',
      meanings: ['思い出', '友情', '初恋'],
      colorMeanings: [
        { color: '紫', hex: '#9a78dc', meanings: ['初恋', '恋の芽生え'] },
        { color: '白', hex: '#f6f3ee', meanings: ['青春の喜び', '無邪気'] }
      ],
      categories: ['friendship', 'love', 'comfort'],
      recipients: ['friend', 'partner'],
      scenes: ['graduation', 'confession'],
      season: '4〜5月',
      description: '小さな花が房になって咲く、香りのよい花木です。',
      origin: '春の訪れとともに甘く香り、若い日々を思い出させることから「思い出」「初恋」といわれます。',
      trivia: 'フランス語では「リラ」と呼ばれます。札幌市の木としても親しまれています。',
      message: 'あの日の思い出が、今日のあなたを支えています。',
      point: '「友情」「思い出」。同級生や旧友に。',
      look: { shape: 'cluster', colors: ['#cdb5ee', '#a887dd', '#f0e8fb'] }
    },
    {
      id: 'lavender', name: 'ラベンダー', kana: 'らべんだー', emoji: '💜',
      meanings: ['あなたを待っています', '期待', '清潔', '沈黙'],
      categories: ['hope', 'comfort', 'love'],
      recipients: ['partner', 'friend', 'special'],
      scenes: ['farewell', 'visit'],
      season: '6〜8月',
      description: '心やすらぐ香りと紫の穂が美しいハーブです。',
      origin: '古くから入浴や洗濯に使われたことから「清潔」、再会を待つ想いを重ねて「あなたを待っています」といわれます。',
      trivia: '名前はラテン語で「洗う」を意味する言葉が由来とされます。北海道・富良野のラベンダー畑が有名です。',
      message: '深呼吸をひとつ。いい知らせを待ちましょう。',
      point: '「あなたを待っています」。離れて暮らす人に。',
      look: { shape: 'spike', colors: ['#b7a0e6', '#8d6fd3', '#dcd0f5'] }
    },
    {
      id: 'gentian', name: 'リンドウ', kana: 'りんどう', emoji: '💙',
      meanings: ['誠実', '正義', '悲しんでいるあなたを愛する'],
      categories: ['sincerity', 'health', 'respect', 'comfort'],
      recipients: ['parents', 'teacher', 'family'],
      scenes: ['thanks', 'fathersday'],
      season: '9〜11月',
      description: '秋の野に青紫の筒形の花を咲かせる、日本の山野草です。',
      origin: '群れずにすっと咲く凛とした姿から「誠実」「正義」、苦い根が薬として人を助けたことから人を気づかう花言葉が生まれました。',
      trivia: '根が竜の胆のように苦いことから「竜胆」と書きます。敬老の日の贈り物としても人気です。',
      message: 'まっすぐなあなたを、ちゃんと見ている人がいます。',
      point: '「誠実」。敬老の日や、お父さんへの贈り物に。',
      look: { shape: 'trumpet', colors: ['#8b9ae6', '#5a67c9', '#e1e5fb'] }
    },
    {
      id: 'forget-me-not', name: 'ワスレナグサ', kana: 'わすれなぐさ', emoji: '💙',
      meanings: ['私を忘れないで', '真実の友情', '誠の愛'],
      categories: ['friendship', 'love', 'comfort'],
      recipients: ['friend', 'partner', 'special'],
      scenes: ['farewell', 'graduation'],
      season: '3〜5月',
      description: '空色の小さな花が愛らしい、春の花です。',
      origin: 'ドイツの伝説で、恋人のために川辺の花を摘もうとした騎士が流され「私を忘れないで」と叫んだという物語が由来です。',
      trivia: '英語名の「Forget-me-not」を訳したのが和名「勿忘草」です。',
      message: '遠く離れても、この気持ちは色あせません。',
      point: '「私を忘れないで」。卒業や送別に。',
      look: { shape: 'round', colors: ['#a7cdf2', '#6ea6e0', '#f5d55c'] }
    }
  ];
})();
